### ISSUE TITLE
Tag a Version

### ISSUE THREAD

**Issue by JesseKPhillips** [opticron/ProtocolBuffer#33]
In order for dub to add a package it requires there be a version tagged (of the format v0.0.0).

I'd also like to take use dub dependencies to pull in the code generator[1], but dub doesn't support D1 compilers. Could the generator support generating for D1 but not compiling using a D1 compiler? I know we've discussed it before, just want to check your pulse now that it's been 3 years :).

1. https://github.com/JesseKPhillips/codebuilder

**Comment by opticron** [comment]
At this point, the landscape has changed enough that I'm willing to ditch
D1 support entirely if it's causing problems. Feel free to start removing
D1 compilability where it's holding you back.

**Comment by opticron** [comment]
I went ahead and created v0.0.0 for the starting version with D1 and D2 support for compilation and generation so someone can get it if they need it.
